#!/bin/zsh

# vim:set noet sts=0 sw=4 ts=4 foldmethod=marker:

################################################################################
# This file is sourced only for interactive shells. It
# should contain commands to set up aliases, functions,
# options, key bindings, etc.
#
# Global Order: zshenv, zprofile, zshrc, zlogin
################################################################################

source ~/.zsh/grml-etc-core/etc/zsh/zshrc
fpath=(~/.zsh/grml-etc-core/usr_share_grml/zsh/ $fpath)

stty -ixon

. ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
. ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh

# {{{ Prompt Setup Information

BLUE="%F{blue}"
RED="%F{red}"
GREEN="%F{green}"
CYAN="%F{14}"
MAGENTA="%F{13}"
YELLOW="%F{11}"
WHITE="%F{white}"

grml_prompt_pre_default[user]="$CYAN"
grml_prompt_pre_default[at]="$MAGENTA"
grml_prompt_pre_default[host]="$CYAN"
grml_prompt_pre_default[jobs]="$CYAN"
grml_prompt_pre_default[path]="$MAGENTA"
grml_prompt_pre_default[time]="$CYAN"
grml_prompt_pre_default[percent]="%(?.%2F.%1F)"
grml_prompt_post_default[percent]="%f"

grml_prompt_token_default[time]="%D{%H:%M:%S} "

grml_vcs_coloured_formats=(
    format "${MAGENTA}(${CYAN}%s${MAGENTA})${YELLOW}-${MAGENTA}[${CYAN}%b${MAGENTA}]${NO_COLOR} "
    actionformat "${MAGENTA}(${NO_COLOR}%s${MAGENTA})${YELLOW}-${MAGENTA}[${GREEN}%b${YELLOW}|${RED}%a${MAGENTA}]${NO_COLOR} "
    rev-branchformat "%b${RED}:${YELLOW}%r"
)

# required because reasons? dunno.
grml_vcs_info_set_formats coloured

function prompt_grml_precmd () {
    emulate -L zsh
    local grmltheme=grml
    local -a left_items right_items
    left_items=(rc change-root user at host path vcs time percent)
    right_items=()

    prompt_grml_precmd_worker
}

# }}}

test -f ~/.zsh/rc.post && source ~/.zsh/rc.post

patch_zip() {
	unzip $1 $2
	${EDITOR:-vim} $2
	zip -g $1 $2
}

if test -d ~/.zsh/rc.d; then
	for f in "$HOME"/.zsh/rc.d/*; do
		. "$f"
	done
fi

true
