---
# vim: set et ts=2 sw=2:
- name: Set up GnuPG config directory
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/.gnupg"
- name: Default GnuPG agent config
  blockinfile:
    block: |
      enable-ssh-support
      keep-display
    create: true
    marker: "# {mark} Ansible block - Default GnuPG agent config"
    path: "{{ ansible_env.HOME }}/.gnupg/gpg-agent.conf"
- name: Disable GnuPG services
  systemd:
    scope: user
    name: "{{ item }}"
    masked: true
  with_items:
    - gpg-agent.socket
    - gpg-agent-extra.socket
    - gpg-agent-ssh.socket
    - gpg-agent-browser.socket
- name: Install systemd unit
  copy:
    src: gpg-agent-custom.service
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/gpg-agent-custom.service"
- name: Enable GnuPG services
  systemd:
    scope: user
    name: gpg-agent-custom.service
    state: started
    enabled: true
    daemon_reload: true
